Exercise 1:\
Abstract: In this exercise, a paired sample t-test is conducted to evaluate the impact of backend optimization techniques on website response time. Performance measurements collected before and after optimization for the same test cases are analyzed to determine whether the observed reduction in response
time is statistically significant. This exercise helps students develop analytical skills in performance evaluation and evidence-based system optimization using inferential statistics.

In [1]:
import pandas as pd
import numpy as np
from scipy import stats

In [2]:
data = {
    "Test_Case": ["T1","T2","T3","T4","T5","T6","T7","T8"],
    "Response_Time_Before": [420, 450, 410, 470, 440, 460, 430, 445],
    "Response_Time_After": [360, 390, 355, 400, 380, 395, 370, 385]
}
df = pd.DataFrame(data)
df

  Test_Case  Response_Time_Before  Response_Time_After
0        T1                   420                  360
1        T2                   450                  390
2        T3                   410                  355
3        T4                   470                  400
4        T5                   440                  380
5        T6                   460                  395
6        T7                   430                  370
7        T8                   445                  385

In [3]:
df["Difference"] = df["Response_Time_Before"] - df["Response_Time_After"]
df

  Test_Case  Response_Time_Before  Response_Time_After  Difference
0        T1                   420                  360          60
1        T2                   450                  390          60
2        T3                   410                  355          55
3        T4                   470                  400          70
4        T5                   440                  380          60
5        T6                   460                  395          65
6        T7                   430                  370          60
7        T8                   445                  385          60

In [4]:
t_statistic, p_value = stats.ttest_rel(
    df["Response_Time_Before"],
    df["Response_Time_After"]
)
t_statistic, p_value

(np.float64(39.08847772565582), np.float64(1.8674871068411005e-09))

In [5]:
print("Paired Sample t-test Results")
print("----------------------------")
print(f"t-statistic: {t_statistic:.4f}")
print(f"p-value: {p_value:.4f}")

Paired Sample t-test Results
----------------------------
t-statistic: 39.0885
p-value: 0.0000

In [6]:
alpha = 0.05
if p_value < alpha:
    print("Conclusion: The reduction in response time is statistically significant.")
else:
    print("Conclusion: The reduction in response time is NOT statistically significant.")

Conclusion: The reduction in response time is statistically significant.

Null Hypothesis (H₀): There is no significant difference in the website response time before and after applying backend optimization techniques. Any
observed reduction in response time is due to random variation.\
Alternative Hypothesis (H₁): There is a significant reduction in the website response time after applying backend optimization techniques.\
The paired sample t-test compares response times measured before and after backend optimization for the same test cases. Since the
calculated p-value is less than the significance level (α = 0.05), the null hypothesis is rejected. This indicates that backend optimization
techniques have significantly reduced website response time, proving their effectiveness through statistical evidence.

Exercise 2:\
Abstract: This exercise involves applying a one-sample t-test to analyze daily electricity consumption recorded from smart energy meters. The objective is to examine whether the average energy usage of households significantly differs from a predefined standard consumption level. Students will analyze the data by framing appropriate hypotheses, calculating the test statistic, and interpreting the results to support datadriven decisions related to energy efficiency and consumption monitoring.

In [7]:
data = {
    "Household_ID": ["H1","H2","H3","H4","H5","H6","H7","H8","H9","H10"],
    "Daily_Energy_Consumption": [11.2, 10.8, 11.5, 10.6, 11.0, 11.3, 10.9, 11.1, 10.7, 11.4]
}
df = pd.DataFrame(data)
df

  Household_ID  Daily_Energy_Consumption
0           H1                      11.2
1           H2                      10.8
2           H3                      11.5
3           H4                      10.6
4           H5                      11.0
5           H6                      11.3
6           H7                      10.9
7           H8                      11.1
8           H9                      10.7
9          H10                      11.4

In [9]:
population_mean = 11  # kWh
t_statistic, p_value = stats.ttest_1samp(
    df["Daily_Energy_Consumption"],
    population_mean
)
t_statistic, p_value

(np.float64(0.5222329678671007), np.float64(0.6141172548083891))

In [10]:
print("One-Sample t-test Results")
print("-------------------------")
print(f"t-statistic: {t_statistic:.4f}")
print(f"p-value: {p_value:.4f}")

One-Sample t-test Results
-------------------------
t-statistic: 0.5222
p-value: 0.6141

In [11]:
alpha = 0.05
if p_value < alpha:
    print("Conclusion: The average daily energy consumption significantly differs from the assumed mean.")
else:
    print("Conclusion: The average daily energy consumption does NOT significantly differ from the assumed mean.")

Conclusion: The average daily energy consumption does NOT significantly differ from the assumed mean.

Null Hypothesis (H₀): The average daily energy consumption of households recorded by smart energy meters is equal to the assumed standard consumption
level of 11 kWh.\
Alternative Hypothesis (H₁): The average daily energy consumption of households is different from the assumed standard consumption level of 11 kWh.\
A one-sample t-test was performed to compare the mean daily energy consumption of households with the assumed population mean
of 11 kWh. The calculated p-value is greater than the significance level (α = 0.05), hence the null hypothesis is not rejected. This
indicates that the average daily electricity consumption does not significantly differ from the standard consumption level. Therefore,
household energy usage is consistent with the expected benchmark, supporting effective energy monitoring.